### ISSUE TITLE
Move the "categorical values" query into this repo

### ISSUE THREAD

**Issue by evansd** [opensafely/tpp-database-schema#185]
We have a separate project which fetches the possible values for categorical columns in the database:
https://github.com/opensafely/tpp-database-categorical-columns

Conceptually, this would fit well in this repo which already fetches the contents of the data dictionary as well as the table schema. Consolidating these into one repo reduces the number of moving parts and makes it easier to automate the process of pulling the categorical values into the ehrQL repo as we currently do with the schema and data dictionary.

At a minimum, we should move both of the SQL scripts below into this repo and add appropriate actions for them:
https://github.com/opensafely/tpp-database-categorical-columns/tree/c644869927be18196f4922637ad2e9a02d8549a4/analysis

Once that's done the repo can be archive and the corresponding workspace mothballed (in whatever is the appropriate way):
https://jobs.opensafely.org/opensafely-internal/tpp-database-categorical-columns/

However, I also think it would worth taking the opportunity to slightly change the approach here. The existing categorical value scripts use ehrQL's table and column names rather than the database ones e.g. `practice_registrations.practice_stp` where the actual underlying column is `Organisation.STPCode`. I think this is incorrect because the aim of this repo is to accurately report on the structure and contents of the TPP database, which is independent of how we choose to present it in ehrQL. It's also misleading in that it reports the underlying database values with the ehrQL column names e.g. the categories returned by ehrQL's `patients.sex` are not the same as the categories in the `Patient.Sex` column.

I don't think there's much more to this than updating the table and column names used in the query to match what appears in the SQL. But I think once that's done the distinction between `core` and `tpp` no longer makes sense and the two files should be combined into one.

Slack discussion:
https://bennettoxford.slack.com/archives/C63UXGB8E/p1730883101028639

**Comment by madwort** [comment]
follow-up issue https://github.com/opensafely/tpp-database-categorical-columns/issues/8
