### ISSUE TITLE
Schema does not include collations for string columns

### ISSUE THREAD

**Issue by evansd** [opensafely/tpp-database-schema#50]
This is **not** a defect in this repo – it is something only TPP can fix for us – but this felt like the most appropriate place to record it for future reference.

---

The schema table does not tell us the collation of string columns:

DataSource | TableName | ColumnName | ColumnType | Precision | Scale | MaxLength | IsNullable
-- | -- | -- | -- | -- | -- | -- | --
ICNARC | ICNARC | HRG | varchar | 0 | 0 | 50 | TRUE
ICNARC | ICNARC | ICNARC_ID | bigint | 19 | 0 | 8 | TRUE
... |   |   |   |   |   |   |  

We know that there are some columns whose collation differs from the database default e.g.
 * `MedicationDictionary.DMD_ID` has collation `Latin1_General_CI_AS`
 * `CodedEvent.CTV3Code` has collation `Latin1_General_BIN`

Collations are relevant when comparing columns between tables (or between tables and temporary tables) because the collations must be compatible in order for the comparison to be valid. In particular, if want to create a temporary table with the contents of a codelist and then join that to an event table (`ON temp_codelist.code == event_table.code`) then we need to know the collation of `event_table.code` in order to create `temp_codelist` with a compatible collation.

For now we manually inject the collations we know about into our test schema. But it would be better if these were included automatically.

**Comment by iaindillingham** [comment]
Just seen this. Thanks, @evansd.
